server:
  port: 8999

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JustinChen41/sportmall-config.git
          username: jtchen0401@163.com
          password: chenjianting0401
          force-pull: true